modLoader="javafml"
loaderVersion="[42,)"
license="All rights reserved"

[[mods]]
modId="rift"
version="0.0.1"
displayName="Prehistoric Rift"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="pack_icon.png"
authors="ANightDazingZoroark"
credits="Thanks for this example mod goes to Java"
description='''
Originally made for the Bedrock Edition, this mod aims to add dinosaurs and other prehistoric creatures and expand upon gameplay.
'''

[[dependencies.rift]]
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rift]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rift]]
modId="geckolib"
mandatory=true
versionRange="[4.1.2,)"
ordering="NONE"
side="BOTH"